LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := VanzoSoundRecorder
LOCAL_OVERRIDES_PACKAGES := SoundRecorder
LOCAL_MODULE_TAGS := optional
ifeq ($(strip $(VANZO_FEATURE_SOUNDRECORD_SUPPORT_O0)), yes)
LOCAL_SRC_FILES := SoundRecorder_97_o0.apk
else
LOCAL_SRC_FILES := SoundRecorder_39_o1.apk
endif
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)
